### PR TITLE
Don't show workflow name if it's only one

### PR DESCRIPTION
**Pull request by qwerty287**
Was introduced by https://github.com/woodpecker-ci/woodpecker/pull/1304.

If there's only one workflow, don't make it collapsible and don't show the name of it.

### CODE REVIEW

**Comment by lukashass** [comment]
`mt-1` of the steps has to be disabled for the first one in this case, as well:

image

**Comment by 6543** [comment]
I have no strong preference for/against it ... so lgtm

**Comment by 6543** [comment]
@qwerty287 

`src/components/repo/pipeline/PipelineProcList.vue(93,84): error TS2532: Object is possibly 'undefined'.`

**Review by 6543 — APPROVED** [review]
